CLASS /esrcc/bp_i_costelmenetcharact DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF /esrcc/i_costelmenetcharacte_s .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /ESRCC/BP_I_COSTELMENETCHARACT IMPLEMENTATION.
ENDCLASS.
